AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - sit
      - uat
      - prod
Resources:
  EmployeeManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: EmployeeManagementApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: "'true'"

  EmployeeManagementLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: dist/lambda/handler.commonHandler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 120
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub 'employee-management-data-table-${Environment}'
        - DynamoDBCrudPolicy:
            TableName: !Sub 'employee-management-login-table-${Environment}'
      Environment:
        Variables:
          EMP_DATA_TABLE_NAME: !Sub 'employee-management-data-table-${Environment}'
          EMP_LOGIN_TABLE_NAME: !Sub 'employee-management-login-table-${Environment}'
          IS_OFFLINE: 'false'
      Events:
        CreateEmployee:
            Type: Api
            Properties:
              Path: /employee/add
              Method: ANY #post
        GetEmployee:
          Type: Api
          Properties:
            Path: /employee/{id}
            Method: ANY #get
        GetEmployeeList:
          Type: Api
          Properties:
            Path: /employee/list
            Method: ANY #get
        DeleteEmployee:
          Type: Api
          Properties:
            Path: /employee/delete/{id}
            Method: ANY #delete
        UpdateEmployee:
            Type: Api
            Properties:
              Path: /employee/update/{id}
              Method: ANY #put
        Login:
          Type: Api
          Properties:
            Path: /employee/login
            Method: ANY #post

  EmployeeDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'employee-management-data-table-${Environment}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EmployeeLoginTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'employee-management-login-table-${Environment}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
